//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genetic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evolution_History
    {
        public long ID { get; set; }
        public string DNA { get; set; }
        public Nullable<int> Generation_Number { get; set; }
        public Nullable<int> World_Number { get; set; }
        public Nullable<decimal> Elapsed_Time { get; set; }
        public Nullable<decimal> Fitness { get; set; }
        public Nullable<decimal> Weighted_Fitness { get; set; }
    }
}
